[build]
  command = "cd netlify/functions && npm install && cd ../../client && npm install && npm run build"
  publish = "client/build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
